steps:
# Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0",
      "."
    ]

# Push Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0"
    ]

# Get GKE credentials
- name: gcr.io/cloud-builders/gcloud
  args:
    [
      "container",
      "clusters",
      "get-credentials",
      "hello-cluster",
      "--zone",
      "us-central1-c"
    ]

# Deploy to prod namespace
- name: gcr.io/cloud-builders/kubectl
  args:
    [
      "apply",
      "-f",
      "prod/deployment.yaml",
      "-n",
      "prod"
    ]
  env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
    - "CLOUDSDK_CONTAINER_CLUSTER=hello-cluster"

images:
- "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0"
steps:
# Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0",
      "."
    ]

# Push Docker image
- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0"
    ]

# Get GKE credentials
- name: gcr.io/cloud-builders/gcloud
  args:
    [
      "container",
      "clusters",
      "get-credentials",
      "hello-cluster",
      "--zone",
      "us-central1-c"
    ]

# Deploy to prod namespace
- name: gcr.io/cloud-builders/kubectl
  args:
    [
      "apply",
      "-f",
      "prod/deployment.yaml",
      "-n",
      "prod"
    ]
  env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
    - "CLOUDSDK_CONTAINER_CLUSTER=hello-cluster"

images:
- "us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0"

