steps:
  # Build Go app
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', 'main.go']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0',
        '.'
      ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0'
      ]

  # Deploy to GKE (prod)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'prod/deployment.yaml', '-n', 'prod']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

