apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: us-east1-docker.pkg.dev/qwiklabs-gcp-04-2d55124ba7da/my-repository/sample-app:v1.0
          ports:
            - containerPort: 8080
